### ISSUE TITLE
CocoaPods.org does not show the Expand tab for GeoFeatures

### ISSUE THREAD

**Issue by tonystone** [tonystone/geofeatures#62]
After investigation this way be caused by CocoaDocs failing on the following error pulled from this link

http://api.cocoadocs.org:4567/error/GeoFeatures/1.2.0

```
report_error({"message":"Argument list too long - du -skc /Users/maddern/dev/cocoadocs.org/activity/download/GeoFeatures/1.2.0/GeoFeatures/LICENSE /Users/maddern/dev/cocoadocs.org/activity/download/GeoFeatures/1.2.0/GeoFeatures/GeoFeatures/boost/algorithm/minmax_element.hpp ...
/Users/maddern/dev/cocoadocs.org/activity/download/GeoFeatures/1.2.0/GeoFeatures/LICENSE_BOOST_1_0 /Users/maddern/dev/cocoadocs.org/activity/download/GeoFeatures/1.2.0/GeoFeatures/README.md","trace":["/Users/maddern/dev/cocoadocs.org/classes/stats_generator.rb:95:in ``'","/Users/maddern/dev/cocoadocs.org/classes/stats_generator.rb:95:in `generated_install_size'","/Users/maddern/dev/cocoadocs.org/classes/stats_generator.rb:26:in `upload'","/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:484:in `document_spec'","/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:532:in `document_spec_at_path'","/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:165:in `block in doc'","/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:160:in `each'","/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:160:in `doc'","/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:232:in `block in cocoadocs_url'","/Users/maddern/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:153:in `open_uri'","/Users/maddern/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:704:in `open'","/Users/maddern/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:34:in `open'","/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:229:in `cocoadocs_url'","/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:180:in `cocoadocs'","/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:115:in `initialize'","/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:551:in `new'","/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:551:in `<main>'"]}
```

This is due to CocoaDocs trying to document all the internal code and boost which it should not.

Please see the following link for trouble shooting http://orta.io/rebase/why-cant-i-expand/.

**Comment by tonystone** [comment]
So according to what I've read, CocoaDocs is supposed to ignore anything listed in private_header_files so I'm going to explicitly list them.

**Comment by tonystone** [comment]
Unfortunately we can't list them boost headers in the private_header_files list since it causes an issue with xcode.  Looks like we will have to live with this unless the CocoaPods guys come up with a different way to handle the line length.

See neonichu comments in https://github.com/CocoaPods/cocoapods-packager/issues/92

**Comment by tonystone** [comment]
Unfortunately we can't list them boost headers in the private_header_files list since it causes an issue with xcode. Looks like we will have to live with this unless the CocoaPods guys come up with a different way to handle the line length.

See neonichu comments in CocoaPods/cocoapods-packager#92
